# -*- coding: utf-8 -*-
"""simulation code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h69qLg7hRbn5_oOLU-RLjm3rTdCsh4mI
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
from scipy.ndimage import gaussian_filter1d
import time
# === Model Parameters ===

# --- Model parameters ---
S0 = 1200
L = 1.0
epsilon = 0.5
sigma = 5.67e-8

# --- Forcing Cycle ---
solar_amplitude = 0.5
solar_period_kyr = 25.0

# --- Growth Preferences ---
T_opt_white = 10
T_opt_black = -10
T_range = 10
death_rate = 0.01

# --- Death Rates ---
use_asymmetric_death = False
asym_death_hot_scale = 0.01
asym_death_cold_scale = 0.02
asym_death_exponent = 1.5


# --- Perturbation Control ---
use_perturbations = True
perturbation_strength = 0.001

# --- Simulation Control ---
steps = 2000
years_per_step = 0.1
initial_daisy_area = 0.02
baseline_fraction = 0.07
use_transport = True
transport_strength = 0.05
transport_steps = 10

# --- Albedos ---
alpha_white = 0.8
alpha_black = 0.2
alpha_soil = 0.3

# --- More Toggles ---
use_random_solar_phase = False
use_baseline_drift = False
use_solar_jumps = False
use_density_feedback = True
variable_death_rate_enabled = True
enable_feedback_delay = True
enable_cloud_reflection = True

# --- More Parameters ---
baseline_drift_per_kyr = 0.05  # W/m^2 per 1000 years
solar_jump_magnitude = 0.1     # 10% sudden drop/spike
solar_jump_frequency = 500     # once every 500 steps
feedback_delay_steps = 1       # how many steps behind for T use
cloud_albedo_factor = 0.05     # how much daisy coverage reduces soil albedo



with st.expander("Solar Forcing"):
    S0 = st.slider("Base Solar Constant (S0)", 1000, 1400, 1200)
    solar_amplitude = st.slider("Solar Amplitude", 0.0, 1.0, 0.5)
    solar_period_kyr = st.slider("Solar Period (kyr)", 1.0, 100.0, 25.0)
    use_random_solar_phase = st.checkbox("Random Solar Phase", False)
    use_baseline_drift = st.checkbox("Baseline Drift", False)
    baseline_drift_per_kyr = st.slider("Baseline Drift per kyr", 0.0, 0.2, 0.05)
    use_solar_jumps = st.checkbox("Enable Solar Jumps", False)
    solar_jump_magnitude = st.slider("Solar Jump Magnitude", 0.0, 0.5, 0.1)
    solar_jump_frequency = st.number_input("Solar Jump Frequency (steps)", 100, 5000, 500, step=100)

with st.expander("Daisy Growth"):
    T_opt_white = st.slider("White Daisy Optimal Temp (°C)", -30, 30, 10)
    T_opt_black = st.slider("Black Daisy Optimal Temp (°C)", -30, 30, -10)
    T_range = st.slider("Growth Temp Range", 1, 50, 10)
    death_rate = st.number_input("Base Death Rate", 0.0, 0.1, 0.01)

with st.expander("Death Behavior"):
    variable_death_rate_enabled = st.checkbox("Enable Variable Death Rate", True)
    use_asymmetric_death = st.checkbox("Asymmetric Death Penalty", False)
    asym_death_hot_scale = st.slider("Hot-side Death Scale", 0.0, 0.1, 0.01)
    asym_death_cold_scale = st.slider("Cold-side Death Scale", 0.0, 0.1, 0.02)
    asym_death_exponent = st.slider("Hot-side Death Exponent", 1.0, 3.0, 1.5)

with st.expander("Planetary Transport & Feedback"):
    use_transport = st.checkbox("Enable Energy Transport", True)
    transport_strength = st.slider("Transport Strength", 0.0, 0.2, 0.05)
    transport_steps = st.number_input("Transport Iterations", 1, 50, 10)
    use_density_feedback = st.checkbox("Density Feedback on Capacity", True)
    enable_feedback_delay = st.checkbox("Enable Feedback Delay", True)
    feedback_delay_steps = st.number_input("Feedback Delay Steps", 0, 20, 1)
    enable_cloud_reflection = st.checkbox("Enable Cloud Reflection", True)
    cloud_albedo_factor = st.slider("Cloud Albedo Boost", 0.0, 0.2, 0.05)

with st.expander("Perturbation & Simulation Control"):
    use_perturbations = st.checkbox("Enable Perturbations", True)
    perturbation_strength = st.slider("Perturbation Strength", 0.001, 0.1, 0.001)
    steps = st.number_input("Simulation Steps", 1000, 100000, 2000, step=1000)
    years_per_step = st.number_input("Millenia per Step", 0.001, 1.0, 0.1)
    initial_daisy_area = st.slider("Initial Daisy Area", 0.0, 0.1, 0.02)
    baseline_fraction = st.slider("Baseline Forcing Fraction", 0.0, 0.2, 0.07)

with st.expander("Albedo Settings"):
    alpha_white = st.slider("White Daisy Albedo", 0.0, 1.0, 0.8)
    alpha_black = st.slider("Black Daisy Albedo", 0.0, 1.0, 0.2)
    alpha_soil = st.slider("Soil Albedo", 0.0, 1.0, 0.3)




# === Latitude Setup ===
latitudes = np.arange(-90, 91, 1)
cos_lat = np.clip(np.cos(np.deg2rad(latitudes)), 1e-3, None)
area_weights = cos_lat / np.sum(cos_lat)
rel_insol = np.array([np.cos(np.deg2rad(lat)) for lat in latitudes])

# === Solar Forcing ===
def solar_constant(time_kyr, step=None, S0=S0, amplitude=solar_amplitude, period_kyr=solar_period_kyr):
    phase = np.random.uniform(0, 2 * np.pi) if use_random_solar_phase else 0
    forcing = S0 * (1 + amplitude * np.sin(2 * np.pi * time_kyr / period_kyr + phase))

    if use_baseline_drift:
        forcing += baseline_drift_per_kyr * time_kyr

    if use_solar_jumps and step is not None and step % solar_jump_frequency == 0:
        forcing *= (1 - solar_jump_magnitude) if np.random.rand() < 0.5 else (1 + solar_jump_magnitude)

    return forcing
# === Daisy Growth Curve ===
def daisy_growth_rate(T, T_opt, T_range=T_range):
    rate = 1 - ((T - T_opt) / T_range)**2
    return np.clip(rate, 0.0, 1.0)

# === Daisy Area Update ===
def update_daisy_areas(A_white, A_black, T, prev_total=None, death_rate=death_rate):
    g_white = daisy_growth_rate(T, T_opt=T_opt_white)
    g_black = daisy_growth_rate(T, T_opt=T_opt_black)

    total = A_white + A_black
    capacity = 1 - total

    if use_density_feedback and prev_total is not None:
        capacity *= (1 - prev_total)

    def get_death_rate(T, T_opt):
      if not variable_death_rate_enabled:
          return np.full_like(T, death_rate)

      deviation = T - T_opt

      if use_asymmetric_death:
          hot_term = asym_death_hot_scale * (deviation / T_range)**asym_death_exponent
          cold_term = asym_death_cold_scale * (np.abs(deviation) / T_range)
          asymmetric_boost = np.where(deviation > 0, hot_term, cold_term)
          return death_rate + asymmetric_boost
      else:
          return death_rate + 0.01 * (np.abs(deviation) / T_range)


    actual_death_white = get_death_rate(T, T_opt_white)
    actual_death_black = get_death_rate(T, T_opt_black)

    d_white = A_white * (g_white * capacity - actual_death_white)
    d_black = A_black * (g_black * capacity - actual_death_black)

    A_white = np.clip(A_white + d_white, 0.0, 1.0)
    A_black = np.clip(A_black + d_black, 0.0, 1.0)

    total = A_white + A_black
    overfill = np.maximum(total - 1.0, 0.0)
    A_white -= overfill * (A_white / total)
    A_black -= overfill * (A_black / total)

    return A_white, A_black



# === Energy Transport ===
import time

def apply_flux_based_directional_energy_transport(E, strength=0.05, steps=10, timing=None):
    E = E.copy()
    A = cos_lat
    inv_A = 1 / A
    mid = len(E) // 2
    E_max = 1e5

    for _ in range(steps):
        # Northward
        i = np.arange(mid, len(E) - 1)
        delta_flux = (E[i] / A[i]) - (E[i+1] / A[i+1])
        flow = strength * A[i+1] * delta_flux
        flow = np.clip(flow, 0, E[i])  # only positive flow
        E[i] -= flow
        E[i+1] += flow

        # Southward
        i = np.arange(mid, 0, -1)
        delta_flux = (E[i] / A[i]) - (E[i-1] / A[i-1])
        flow = strength * A[i-1] * delta_flux
        flow = np.clip(flow, 0, E[i])
        E[i] -= flow
        E[i-1] += flow

    E = np.clip(E, 0, E_max)


    return E






# === Energy → Temperature ===
def energy_to_temperature(E):
    T_K = (E / (epsilon * sigma * cos_lat))**0.25
    return T_K - 273.15

# === Main Simulation ===
def run_daisyworld_profiled():
    A_white = np.full_like(latitudes, initial_daisy_area, dtype=np.float64)
    A_black = np.full_like(latitudes, initial_daisy_area, dtype=np.float64)
    T_history = np.zeros((steps, len(latitudes)))
    W_history = np.zeros_like(T_history)
    B_history = np.zeros_like(T_history)



    for step in range(steps):
        time_kyr = step * years_per_step
        S_t = solar_constant(time_kyr, step=step)

        total_cover = A_white + A_black
        local_alpha = (
            A_white * alpha_white +
            A_black * alpha_black +
            (1 - total_cover) * alpha_soil
        )

        F_in = S_t * rel_insol * (1 - local_alpha) + baseline_fraction * S_t
        T_K = (L * F_in / (4 * epsilon * sigma))**0.25
        E = epsilon * sigma * T_K**4 * cos_lat

        if use_transport:
            E = apply_flux_based_directional_energy_transport(E, strength=transport_strength, steps=transport_steps)


        T_C = energy_to_temperature(E)
        T_C[0]  = min(T_C[0],  T_C[1])
        T_C[-1] = min(T_C[-1], T_C[-2])

        A_white, A_black = update_daisy_areas(A_white, A_black, T_C)

        if use_perturbations:
            T_C += np.random.uniform(-1, 1, size=T_C.shape) * np.abs(T_C) * perturbation_strength
            A_white += np.random.uniform(-1, 1, size=A_white.shape) * np.abs(A_white) * perturbation_strength
            A_black += np.random.uniform(-1, 1, size=A_black.shape) * np.abs(A_black) * perturbation_strength

            T_C = np.clip(T_C, -273.15, None)
            A_white = np.clip(A_white, 0.0, 1.0)
            A_black = np.clip(A_black, 0.0, 1.0)

            total = A_white + A_black
            overfill = np.maximum(total - 1.0, 0.0)
            A_white -= overfill * (A_white / total)
            A_black -= overfill * (A_black / total)

        T_history[step] = T_C
        W_history[step] = A_white
        B_history[step] = A_black

        if step % 1000 == 0:
            print(f"Step {step}: Global mean T = {np.sum(T_C * area_weights):.2f}°C")


    return T_history, W_history, B_history



import streamlit as st
import matplotlib.pyplot as plt
import numpy as np
from scipy.ndimage import gaussian_filter1d

def plot_daisyworld_diagnostics(
    T_hist, W_hist, B_hist, latitudes, area_weights,
    years_per_step=0.01,
    solar_amplitude=0.5, solar_period_kyr=5.0, S0=1361,
    epsilon=0.5, sigma=5.67e-8, alpha_soil=0.3,
    lat_step=30
):
    steps = T_hist.shape[0]
    time_kyr = np.arange(steps) * years_per_step

    global_T = T_hist @ area_weights
    global_white = W_hist @ area_weights
    global_black = B_hist @ area_weights

    solar_forcing = np.array([
        S0 * (1 + solar_amplitude * np.sin(2 * np.pi * t / solar_period_kyr))
        for t in time_kyr
    ])
    T_eq = ((solar_forcing * (1 - alpha_soil)) / (4 * epsilon * sigma))**0.25 - 273.15

    raw_dT_dt = np.gradient(global_T, years_per_step)
    raw_dT_eq_dt = np.gradient(T_eq, years_per_step)
    raw_dT_diff = raw_dT_dt - raw_dT_eq_dt

    smoothing_sigma = 4
    dT_dt = gaussian_filter1d(raw_dT_dt, sigma=smoothing_sigma)[2:-2]
    dT_eq_dt = gaussian_filter1d(raw_dT_eq_dt, sigma=smoothing_sigma)[2:-2]
    dT_diff = gaussian_filter1d(raw_dT_diff, sigma=smoothing_sigma)[2:-2]
    time_kyr_trimmed = time_kyr[2:-2]

    north_idx = latitudes >= 0

    # === Plot 1: Final state
    fig1, ax = plt.subplots(1, 2, figsize=(12, 5))
    ax[0].plot(latitudes[north_idx], T_hist[-1][north_idx])
    ax[0].set_title("Final Temperature (North Only)")
    ax[0].set_xlabel("Latitude (°)")
    ax[0].set_ylabel("Temperature (°C)")

    ax[1].plot(latitudes[north_idx], W_hist[-1][north_idx], label='White')
    ax[1].plot(latitudes[north_idx], B_hist[-1][north_idx], label='Black')
    ax[1].set_title("Final Daisy Coverage (North Only)")
    ax[1].set_xlabel("Latitude (°)")
    ax[1].set_ylabel("Coverage")
    ax[1].legend()
    st.pyplot(fig1)

    # === Plot 2: Global Temperature
    fig2, ax2 = plt.subplots(figsize=(10, 4))
    ax2.plot(time_kyr, global_T, label='Global T (°C)')
    ax2.set_xlabel("Time (kyr)")
    ax2.set_title("Global Temperature")
    ax2.legend()
    ax2.grid(True)
    st.pyplot(fig2)

    # === Plot 3: Rate of change
    fig3, ax3 = plt.subplots(figsize=(10, 5))
    ax3.plot(time_kyr_trimmed, dT_dt, label='dT/dt (Actual)', color='tab:red')
    ax3.plot(time_kyr_trimmed, dT_eq_dt, label='dT_eq/dt (From Forcing)', color='tab:blue', linestyle='--')
    ax3.axhline(0, color='gray', linestyle='--', linewidth=1)
    ax3.set_xlabel("Time (kyr)")
    ax3.set_ylabel("Rate of Temperature Change (°C/kyr)")
    ax3.set_title("Rate of Change: Actual vs. Equilibrium Temperature")
    ax3.legend()
    ax3.grid(True)
    st.pyplot(fig3)

    # === Plot 4: Deviation
    fig4, ax4 = plt.subplots(figsize=(10, 5))
    ax4.plot(time_kyr_trimmed, dT_diff, label='dT/dt - dT_eq/dt', color='purple')
    ax4.axhline(0, color='gray', linestyle='--', linewidth=1)
    ax4.set_xlabel("Time (kyr)")
    ax4.set_ylabel("Difference in dT/dt (°C/kyr)")
    ax4.set_title("Deviation from Equilibrium Forcing")
    ax4.legend()
    ax4.grid(True)
    st.pyplot(fig4)



#RUN MODEL

T_hist, W_hist, B_hist = run_daisyworld_profiled()
global_T = T_hist @ area_weights
global_white = W_hist @ area_weights
global_black = B_hist @ area_weights

time_kyr = np.arange(len(global_T)) * years_per_step
solar_forcing = np.array([
    solar_constant(t, S0=S0, amplitude=solar_amplitude, period_kyr=solar_period_kyr)
    for t in time_kyr
])
T_eq = ((solar_forcing * (1 - alpha_soil)) / (4 * epsilon * sigma))**0.25 - 273.15


plot_daisyworld_diagnostics(
    T_hist, W_hist, B_hist, latitudes, area_weights,
    years_per_step=years_per_step,
    solar_amplitude=solar_amplitude,
    solar_period_kyr=solar_period_kyr,
    S0=S0, epsilon=epsilon, sigma=sigma, alpha_soil=alpha_soil
)

